### ISSUE TITLE
a11y: fixed (non float) layout

### ISSUE THREAD

**Issue by amitdo** [abartov/bybeconv#1]
Hi Asaf!

When viewed with X2.5 zoom level, the caption and menu occupy most of the window. I'm talking about zooming via the browser built-in feature.

Fixed layout is not accessible to people who need X2-X3.0 magnification.

**Comment by abartov** [comment]
Hi, Amit!

Indeed, that is a problem.  We are working on making the new site mobile-friendly and are reconsidering the fixed layout.  We expect to be ready with an updated design in a couple of months.

**Comment by amitdo** [comment]
Thanks for the great project (פב"י)!

**Comment by amitdo** [comment]
It's much better now. Thanks!

There are still an issue with the display of authors' pictures.
