### ISSUE TITLE
difference between number of works in website dropdown menu and api total_count (and dealing with transient total_count)

### ISSUE THREAD

**Issue by eyaler** [abartov/bybeconv#104]
![image](https://user-images.githubusercontent.com/4436747/147854874-29973aa1-538b-4558-98c1-20dd96f9e629.png)

api returns:

modern=9210 (<9220)

revival=14942 (<14960)

medieval = 3837 (<3842)

not sure if this is a transient thing as i did see revival increasing slowly between api calls. (by the way - if the total_count changes during looping over pages - you need to start over from page=1 otherwise you can miss entries - not sure if this warrants an issue of it's own - but might be a good idea to mention in the docs)

happy yom kinyano shel hatsibur!

**Comment by eyaler** [comment]
duplicate of https://github.com/abartov/bybeconv/issues/21 ?

**Comment by damisul** [comment]
Navigation menu counts all works in db, including non-published.
I've did a PR to only count published works.

**Comment by damisul** [comment]
Also, even after this fix there is a possibility of seeing small discrepancy because we cache values displayed in navigation menu for 24 hours.

So if count of works will be changed, we may need to wait for up to 24 hours until numbers in nav menu will be updated.
