### ISSUE TITLE
Search results are duplicated in several cases

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#11]
For example, search for items created by ״המאירי״.
Several duplicates are displayed in the search results list (2/3, 5/6, 8/9, 25/26)
See attached screenshot
![98F24FDD-9819-4241-A6E4-7E4CF26CE492](https://user-images.githubusercontent.com/66472441/83886674-15039500-a750-11ea-9e48-da9bfaa72eec.png)

**Comment by abartov** [comment]
These search results are correct; it is actually the texts that exist as duplicates, because they were uploaded as part of two different books of stories.  This will be remedied, but by fixing the data; the search code is fine, here.
