### ISSUE TITLE
Create a BaseUser model.

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#110]
It is an entity used to represent *all* users who use the site, i.e. including the 99% who do not log in, but may still want preferences remembered, or to have bookmarks etc. persist across visits (but not across browsers/devices).

The BaseUser has a 1:1 association with *either* a User record *or* a Rails session cookie.

Most things currently linked to users (Bookmarks, preferences, but not Anthologies) are to instead be linked to BaseUsers.

**Comment by damisul** [comment]
As we want to link this BaseUser to db objects like Bookmarks and preferences, we need to create a new table for it.
The problem is not-authorized users. We can I use session_id for it. But perhaps we'll need a way to cleanup them periodically.
Otherwise this table will be growing and growing

**Comment by abartov** [comment]
Yes, it certainly requires a new table.  And yes, base_users **not** associated with permanent user accounts will periodically need to be purged, when the sessions they are associated with gets purged.

Another thing that can help is to make the creation of a BaseUser record be lazy -- i.e. create a record and associate it with the session ID only when a not-logged-in person actually *sets* a bookmark or makes a preference (e.g. dismisses a particular site-notice).

**Comment by damisul** [comment]
Here is a PR for adding model and some helper code related to it: https://github.com/abartov/bybeconv/issues/110

Will move linked object like preferences and bookmarks in a separate PR

**Comment by damisul** [comment]
Second PR: https://github.com/abartov/bybeconv/pull/120
