### ISSUE TITLE
Reject invalid pages in browsing requests

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#115]
We routinely get bot/spider-generated requests like:

/works/all?page=1359&to_letter=%D7%98"

(whereas we have no more than 300-odd pages right now even when browsing all works.)
I don't know how/why those bots get the idea to look for such a high page number, but it's generating errors and wasting server time.

We need to add a validity check for the page parameter as early as possible (as soon as total result count is known), and if it's invalid, stop processing immediately and return a 4xx HTTP result code.

**Comment by damisul** [comment]
Hm... From what I'm seeing this is not related to spider's, it is same error as we seen here: https://github.com/abartov/bybeconv/issues/100

You can see it from here: https://benyehuda.org/works
Just try to set page to 101 or above (to exceed ElasticSearch's default limit of 10000).

So to fix this we need to set index.max_result_window option on Manifestation index to value greater than total number of works in DB.

It seems that Chewy will overwrite index settings on next reindex, so I've added this setting to index definition.
See this PR https://github.com/abartov/bybeconv/issues/115

**Comment by abartov** [comment]
I do think it is a separate issue, because, as the log line above shows, the page requested (**1359**!) is one that could not have been generated by any link on the site, even when the search result window allows all works (~31k as of today).

**Comment by damisul** [comment]
Ok, here is the second PR to render Not Found status in such sturations: https://github.com/abartov/bybeconv/pull/124
