### ISSUE TITLE
Not used preferences

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#121]
I see 5 preferences defined for users:
```
    property :fontsize, default: DEFAULT_FONT_SIZE
    property :volunteer, default: 'false' # boolean  (another option - :protected => true)
    property :activated, default: 'false' # boolean
    property :suppress_anthology_intro, default: 'false'
    property :jump_to_bookmarks
```
But looks like only fontsize and jumps_to_bookmarks are actually used.
Moreover, I cannot find a place in UI, where fontsize is set. There is a partial with corresponding JS (https://github.com/abartov/bybeconv/blob/master/app/views/shared/_fontsize_js.html.haml) but looks like it is not included from anywhere.

So I would propose to remove unused preferences and clenup related code.
As for fontsize, we have this preference lookup in every call to system, see ApplicationController.set_font_size

**Comment by abartov** [comment]
Yes, these can be removed.
