### ISSUE TITLE
ApplicationController.randomize_works_by_genre hardcodes poetry genre

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#128]
See https://github.com/abartov/bybeconv/blob/d9bee5bd8a16cb6f0d186001845f0a6f4b968544/app/controllers/application_controller.rb#L180

As far as I see it is expected to return random work by genre (it is used from ManifestationController.get_random)

**Comment by abartov** [comment]
Thank you. Indeed, this seems to have been left hard-coded for testing. It was not being called by current code; it had been used by genre-specific portal pages that are no longer used.
