### ISSUE TITLE
Remove manifestations_people table

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#133]
Excert from telegram discussion:

> Q: Quick question. What is the meaning of manifestations_people table? Is it some legacy table used to implement authors?
> A: yes, it is an old table that I created based on the theoretical framework of FRBR, but I've actually found no use for it.  It should be removed.

**Comment by damisul** [comment]
@abartov , before removal of manifestations_people table, I'd like to ensure no useful data would be lost with this change.

I've created SQL query to display all manifestations_people records where we don't have corresponding author record in creations or realizers table:

```
select
  mp.manifestation_id, mp.person_id, p.name as person_name, m.title
from
  manifestations_people mp
  join people p on mp.person_id = p.id
  join manifestations m on mp.manifestation_id = m.id
where
  not exists (
    select 1 from creations c
        join works w on w.id = c.work_id
        join expressions_works ew on w.id = ew.work_id
        join expressions_manifestations em on ew.expression_id = em.expression_id
    where
      c.person_id = mp.person_id
      and mp.manifestation_id = em.manifestation_id
  )
  and not exists (
    select 1 from realizers r
      join expressions_manifestations em on r.expression_id = em.expression_id
    where
      r.person_id = mp.person_id
      and mp.manifestation_id = em.manifestation_id
  );
```
On my db snapshot it returns only 24 records.
Could you please check if those data are OK to loose?

**Comment by abartov** [comment]
Checked on production data.  Confirmed it is okay to remove.  It used to be added by very old code (the create_WEM function, as distinct from the currently-used create_WEM_new).
