### ISSUE TITLE
Search results page - Next/Prev page and First/Last page icons are not displayed

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#14]
When searching for all items by clicking the ״יצירות״ counter on the upper left corner of the main page, a results list is displayed with the Next/Prev page icons and First/Last page icons. 
When searching for a specific value by clicking the search magnifying glass icon, a results list is displayed with the Next/Prev page as text and First/Last page text. 
See attached screenshot 
![45E3F40E-FA39-4326-9288-C0E1BEFC7569](https://user-images.githubusercontent.com/66472441/83888982-42057700-a753-11ea-9377-100a36000ac7.png)

**Comment by abartov** [comment]
Thank you! Fixed.
