### ISSUE TITLE
Expressions without manifestations

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#157]
While working on https://github.com/abartov/bybeconv/issues/156 I've noticed errors on admin#translated_from_multiple_languages page.

The reason was that there are several expressions without corresponding manifestations.
You can see them with following query:

```
select * from expressions e where not exists (select 1 from expressions_manifestations em where em.expression_id = e.id)
```

I can easily fix this by skipping such expressions, but I believe there will be other places where we assume that expression must have manifestation.

So I believe it would be better to fix data issue instead.
We can either create new manifestation (but this will be difficult IMO as we need to add text), or by simply dropping such expressions (with works, creations, realizers, etc)

**Comment by abartov** [comment]
I agree the data should be fixed. On the production DB, though, the SQL query you included yields an empty result set.

**Comment by abartov** [comment]
On my dev environment (with a very old DB, of only ~8000 works) I found four such instances. Safe to delete.

**Comment by abartov** [comment]
My mistake! The empty set was on the (empty) dev environment on the server. There were indeed 11 such expressions on the production DB. I've deleted them and their associated works.
