### ISSUE TITLE
Wrong relations in Proof model

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#160]
Proof model declares user relation twice, see https://github.com/abartov/bybeconv/blob/0d0dd8c73d41bc8762b89526a9f1e905e1d17a1b/app/models/proof.rb#L4

```:ruby
  belongs_to :user, foreign_key: 'reported_by'
  belongs_to :user, foreign_key: 'resolved_by'
```

I believe it should be replaced with something like

```:ruby
  belongs_to :reported_by, class_name: 'User'
  belongs_to :resolved_by, class_name: 'User'
```

**Comment by abartov** [comment]
Yes, that would be better. I _think_ the above used to be the way to do it in Rails 2.x.

**Comment by damisul** [comment]
Hm... I've just checked my copy of db and I see that in all records those columns are empty.
So maybe it would be easier to simply drop those columns?

**Comment by abartov** [comment]
Hmm. The reported_by is indeed useless, as the proofs are being submitted by members of the public, without an account, so shouldn't be a user association, as they are identified by their (optional) email only.
But the 'resolved_by' should record the person who took action on the proof, and if that's not the case now, it should be fixed, in proof_controller.

**Comment by damisul** [comment]
I believe it is fixed in this commit:
https://github.com/abartov/bybeconv/commit/681812c8276bef2e1a9e6fd91dd15c366fe14abd
