### ISSUE TITLE
Strange scope in Publication model

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#161]
Publication model has strange scope 'genre':
https://github.com/abartov/bybeconv/blob/ce4e0b05a094e0f3bcfa4af206ab7cbdc48667b0/app/models/publication.rb#L10

As far as I see it looks like a copy/paste error. So probably it would be better to drop it.

**Comment by abartov** [comment]
Yes, good catch. It is a mistake and isn't used. Please delete.
