### ISSUE TITLE
Google search displays redundant M in the “About” section

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#18]
![60D834BA-12F7-4637-A13B-A0957E8F2FE5](https://user-images.githubusercontent.com/66472441/83938378-5477c300-a7dc-11ea-8074-dd3c3001504a.png)

**Comment by abartov** [comment]
This is an artifact of Google's interpretation of one of our icons.  How it shows up in this auto-generated menu of Google's doesn't bother us enough to be worth the incovenience of changing our layout, so we won't be fixing this.
