### ISSUE TITLE
Switch to Puma web server

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#180]
Project is currently uses thin web server.
Rails uses Puma as default webserver since 5.0, it is more actively developed and is more performant according various benchmarks (e.g. see https://ylan.segal-family.com/blog/2012/08/20/better-performance-on-heroku-thins-vs-unicorn-vs-puma/)

So I would propose to switch to Puma if we don't have any strong reason not to do so

**Comment by abartov** [comment]
Thank you, this was a very good suggestion. I have now switched all our systems to Puma!
