### ISSUE TITLE
Upgrade to Ruby 3.1

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#182]
Well. This is absolutely not urgent.

Upgrading to fresher ruby itself is good idea, as it usually provides more speed and new functionality, but in this particular case I have additional reason.

Last spring I've switched to latest Ubuntu 22.04 (LTS). 
And I got unexpected problem with it: it cannot compile ruby < 3.1 by default. The reason is that this version of Ubuntu ships with fresher openssl v3, and ruby < 3.1 cannot be compiled against it.

So for now I simply use ruby in vagrant . But having ruby in host system would provide more comfortable development experience.

Also I believe at some point we'll need to upgrade our production server as well, and then we'll face this problem anyway.

I've checked if ruby 3.1 can be compiled in Ubuntu Bionic, we use in vagrant and it worked just fine for me. So we should not have problems here in production.

**Comment by abartov** [comment]
Done.
