### ISSUE TITLE
English issue - “About Project Ben Yehuda” should be “About Ben Yehuda Project”

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#19]
As far as my English goes...
I would recommend a native English speaker to review the English About page text.

**Comment by cneta** [comment]
![7D408D32-8018-4DF5-BCF4-9A7291AD5E0C](https://user-images.githubusercontent.com/66472441/83938464-1f1fa500-a7dd-11ea-9b37-324b22a3e0f2.png)

**Comment by abartov** [comment]
Thanks, but we chose the form Project Ben-Yehuda in English (compare: Project Gutenberg).
