### ISSUE TITLE
Error page is displayed when clicking the “contact us” link

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#20]
![C6BD59DE-3F86-4483-8EE3-6D1F6343E0FD](https://user-images.githubusercontent.com/66472441/83938518-981efc80-a7dd-11ea-8917-49aaffdead11.png)

![35A3FF09-1328-4CC2-A625-D49D7FC2842E](https://user-images.githubusercontent.com/66472441/83938521-a53beb80-a7dd-11ea-8595-d8a36e356bea.png)

**Comment by abartov** [comment]
Couldn't reproduce.  Is this still happening for you?

**Comment by cneta** [comment]
Yes. Both in iOS and android. 
Steps to reproduce:
1. Main page, click the hamburger (three lines) on the upper right corner.
2. Click the last option in the menu - “About” | על הפרויקט
3. Click the last option ״יצירת קשר״

Result - the error page is displayed

**Comment by abartov** [comment]
Fixed.
