### ISSUE TITLE
zoom gem does not compile on fresh linux distribution

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#201]
I faced this issue while working on docker-compose configuration.
It turns out that images built on latest stable debian 'bullseye' cannot compile zoom gem (probably due to different version of binary dependencies).
So I had to use oldstable 'buster' image and it compiled successfully.

Did not looked into this deeply but this can become an issue in future if we'll decide to upgrade linux on server.

**Comment by abartov** [comment]
Yeah, I encountered it too. Meanwhile, we can just remove the zoom gem (I have pushed a new version of the gared gem that no longer depends on zoom), as it was only necessary for interfacing with a library catalog software that's been replaced since. I'm going to do that.
