### ISSUE TITLE
text files with fused words

### ISSUE THREAD

**Issue by eyaler** [abartov/bybeconv#216]
searching for files with long or otherwise erroneously fused words, after manual removal of german/yiddish long words, onomatopoeia, slang, etc.  and not including specific final-letter from examples already reported in https://github.com/abartov/bybeconv/issues/214
some are singular cases but some indicate larger issues as in the comments of 1721.txt

here are some files and an example of a fused string therein
txt\enlightenment\28744.txt בעלצחסד
txt\modern\1064.txt עצמהאפשר
txt\modern\15098.txt לסוציולוגיהואנתרופולוגיה
txt\modern\1721.txt הגדודהשניהובילאתהמתקפהוחצהאתהסניולגדתוהצפוניתמולהתנגדותגרמניתלאאחידה
txt\modern\18732.txt באשמותרטרוספקטיביות
txt\modern\25882.txt ברונובסקיהסקוונציה
txt\modern\27753.txt סוציאליסטית’התאחדות’וירצה
txt\revival\1904.txt סמילנסקיואהרונובי
txt\revival\2253.txt אבלצריכה
txt\revival\4078.txt אבלמדוע
txt\revival\5602.txt השחורותוהצעירות
txt\revival\6876.txt וספרהפרטי
txt\revival\8049.txt ביליסווטגרדהבטיחהו
txt\revival\8460.txt ואליוהועברוכלפעולותיושלהבנקהגרמני

**Comment by abartov** [comment]
Thank you very much! We've fixed most of these, and are looking into the issues with 1721.
