### ISSUE TITLE
Filtering all items list by author name gets stuck with thinking animation

### ISSUE THREAD

**Issue by cneta** [abartov/bybeconv#25]
Steps to reproduce:
1. Main page, click the total number of items. 
2.  Items list page, click the filter button (סינון)
3. Filter by name section, click the “author name” option and insert search value (רחל for example). 

Result - the page displays the thinking animation for ever (there is probably an error somewhere in the be/gw/fe - if you can provide me logs access I can add the errors to the bugs)

**Comment by abartov** [comment]
Thank you, fixed.
