### ISSUE TITLE
New tagged pieces appear on the "what's" new list

### ISSUE THREAD

**Issue by eap24** [abartov/bybeconv#289]
Fix bug so that a new tagged work (approved tags) doesn't automatically appear on the "what's new" display.

**Comment by abartov** [comment]
I can't reproduce this issue. Can you give some examples of where it happened?

**Comment by eap24** [comment]
הבחנתי בכך רק פעם אחת כשקיבלתי את התיוגים של מיה ל״שמלת העץ״ של אסתר ראב
