### ISSUE TITLE
Add linters to the project.

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#290]
I propose to add some linters/code analizers to project to ensure that common coding style is used by all developers, and benefit from static code analisys. 

For ruby de-factor standard is a rubocop gem: https://github.com/rubocop/rubocop

We can either use it directly, or we can use some services like CodeClimate (it is free for open-source projects, see https://docs.codeclimate.com/docs/open-source-free). CodeClimate uses many tools under hood, including rubocop.

**Comment by abartov** [comment]
I am happy to add Rubocop and to gradually clean up the code. (But to commit lint/cleanup and actual features or bug fixes separately.)

And it seems CodeClimate doesn't (or no longer does) allow signup without requesting a demo, and demos are bookable only for companies with 100+ employees, so it effectively no longer offers a free tier.

**Comment by damisul** [comment]
Hey, @abartov , please check linked PR.

I've intentinally added violation to a spec, to demonstrate how it will looks like in a case of warning.
Essentially linters checks are only run on lines of code affected by PR, so we should not receive tons of warnings per PR.

I've did some initial tuning of rubocop's config to disable on relax some checks, if you'll feel that some warnings are too noisy we can disable other checks later too.

Also take a look at README, I've added there a section about working with rubocop/pronto.
