### ISSUE TITLE
Author list filtering does not work on mobile

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#294]

**Comment by damisul** [comment]
Well... as far as I see main reason is that for mobile we did not created mobile filter for at all, see: https://github.com/abartov/bybeconv/blob/2529fd8775c0b7e0a551dc5077013fa776e65881/app/views/authors/_mobile_filters.html.haml#L1

We can use same approach as we use in works browse page and render separate form for mobile UI, but I'd like to try to use Bootstrap's adaptive layout. It is a bit tricky, but Bootstrap allows to make same layout to looks differently on mobile and PC.
It maybe hard to keep current look for PC completely the same, but I can try to keep it as close to current look as possible.

Main benefit is that it will greatly simplify js code (as we'll have only one html form on page).
@abartov , WDYT? Can I spend some time to experiment with this?

**Comment by damisul** [comment]
I believe it is duplicate of https://github.com/abartov/bybeconv/issues/318

**Comment by abartov** [comment]
Right, duplicate.
