### ISSUE TITLE
Implement CRUD for CorporateBody

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#307]

**Comment by damisul** [comment]
Hey, @abartov 

I wonder if you started working on this?
If not I can take a look at it. As it maybe a good ticket to introduce simple_form to project (we've discussed this earlier)

**Comment by abartov** [comment]
No, I haven't. I'm still working on a basic user-facing view of a corporate_body's works (equivalent to authors/toc), just something usable to last us until we entirely replace ToC views with Root-collection-based views. Go ahead and implement the CRUD, making sure to limit access to editors, like in authors and manifestations controllers.

**Comment by abartov** [comment]
Please branch off my merge_involved_authorities branch, where I have committed changes to corporate_bodies.

**Comment by abartov** [comment]
Oh, and I'm about to commit some more changes shortly.
