### ISSUE TITLE
Fix routing for addlink rmlink methods in IngestiblesController

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#388]
Currently we have in routes.rb:
```
  match 'ingestibles/:id/rmauth/:seqno' => 'ingestibles#rmauth', as: 'ingestible_remove_authority', via: [:post, :delete]
  post 'ingestibles/:id/addauth' => 'ingestibles#addauth', as: 'ingestible_add_authority'
```

I believe it would be better to define those methods as member actions in ingestibes resrouces instead.
It will change URLs a bit

**Comment by abartov** [comment]
Sure, go ahead.

**Comment by damisul** [comment]
After disucssion in telegram I've extracted those methods into a separate controller IngestibleAuthoritiesController
