### ISSUE TITLE
[API] Implement /texts

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#44]
Implement the /texts endpoint in the /app/api/openapi.yaml spec.

**Comment by damisul** [comment]
Ok, quick update.

1. I've added file_format parameter to the API spec for this endpoint. Same as for texts/batch endpoint: we need to know format to generate download_link
2. There is a question what should be page size? Maybe we need to add separate parameter for this? Currently I've hardcoded 25 as page size
3. What ordering should we apply for pagination? Currently I simply sort by id
4. Very common requirement for pagination is to know how many records in total is out there. Should I return it in response for every page? Or maybe we should have separate endpoint for this?

**Comment by damisul** [comment]
Summary of our discussion over Telegram:
- We need return total records count with every page
- We should implement same sorting options as on main site (and we'll need this for search endpoint too)
