### ISSUE TITLE
Consider using of grape-swagger to get auto-generated swagger documentation

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#60]
I believe we can try to use https://github.com/ruby-grape/grape-swagger to genrate swagger documentation.
I've quickly checked it and it works for params. But it doesn't generates description for response formats.
I believe it can be done with https://github.com/ruby-grape/grape-swagger-entity, but it will require some research

**Comment by abartov** [comment]
If it gets messy, it's probably also worth looking at some non-Ruby-specific documentation generators (based purely on the YAML spec).
