### ISSUE TITLE
Do we need publication_year and title_and_authors in /texts API response?

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#84]
We have 'orig_publication_date'  field, and publication_year simply extract year from same field.

Also title_and_authors is just a concatenation of title and author_string we have in separate fields, so consumer can simply concatenate them if neccessary.

I believe this is some kind of data duplication we can avoid.

**Comment by abartov** [comment]
Yeah, okay, they can be removed. Be sure to remove them from the YAML spec too, please.
